
"""lat lon to locationn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vr_oJCgquckurAeYCZl8oLDvUE1FMa-C
"""

pip install geopy

# module
from geopy.geocoders import Nominatim

# initializethe Nominatim API
geolocator = Nominatim(user_agent="geoapi")

# Latitude & Longitude input
Latitude = "30.594095"
Longitude = "75.137566"
 
location = geolocator.reverse(Latitude+","+Longitude)
 
# Display
print(location)

address = location.raw['address']
print(address)

city = address.get('city', '')
state = address.get('state', '')
country = address.get('country', '')
code = address.get('country_code')
zipcode = address.get('postcode')
print('City : ',city)
print('State : ',state)
print('Country : ',country)
print('Zip Code : ', zipcode)

